package com.kx.exam.mapper;

import com.kx.exam.model.Order;
import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_order
     *
     * @mbg.generated
     */
    int deleteById(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_order
     *
     * @mbg.generated
     */
    Order selectById(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_order
     *
     * @mbg.generated
     */
    int updateById(Order record);
}