package com.kx.exam.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_message.messageid
     *
     * @mbg.generated
     */
    private String messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_message.opuserid
     *
     * @mbg.generated
     */
    private String opuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_message.touserid
     *
     * @mbg.generated
     */
    private String touserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_message.createdate
     *
     * @mbg.generated
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_message.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_message.messageid
     *
     * @return the value of xt_message.messageid
     *
     * @mbg.generated
     */
    public String getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_message.messageid
     *
     * @param messageid the value for xt_message.messageid
     *
     * @mbg.generated
     */
    public void setMessageid(String messageid) {
        this.messageid = messageid == null ? null : messageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_message.opuserid
     *
     * @return the value of xt_message.opuserid
     *
     * @mbg.generated
     */
    public String getOpuserid() {
        return opuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_message.opuserid
     *
     * @param opuserid the value for xt_message.opuserid
     *
     * @mbg.generated
     */
    public void setOpuserid(String opuserid) {
        this.opuserid = opuserid == null ? null : opuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_message.touserid
     *
     * @return the value of xt_message.touserid
     *
     * @mbg.generated
     */
    public String getTouserid() {
        return touserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_message.touserid
     *
     * @param touserid the value for xt_message.touserid
     *
     * @mbg.generated
     */
    public void setTouserid(String touserid) {
        this.touserid = touserid == null ? null : touserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_message.createdate
     *
     * @return the value of xt_message.createdate
     *
     * @mbg.generated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_message.createdate
     *
     * @param createdate the value for xt_message.createdate
     *
     * @mbg.generated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_message.content
     *
     * @return the value of xt_message.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_message.content
     *
     * @param content the value for xt_message.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}