package com.kx.exam.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.orderid
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.productid
     *
     * @mbg.generated
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.amount_first
     *
     * @mbg.generated
     */
    private Double amountFirst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.months
     *
     * @mbg.generated
     */
    private Integer months;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.amount_month
     *
     * @mbg.generated
     */
    private Double amountMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_order.createdate
     *
     * @mbg.generated
     */
    private String createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.orderid
     *
     * @return the value of xt_order.orderid
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.orderid
     *
     * @param orderid the value for xt_order.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.productid
     *
     * @return the value of xt_order.productid
     *
     * @mbg.generated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.productid
     *
     * @param productid the value for xt_order.productid
     *
     * @mbg.generated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.userid
     *
     * @return the value of xt_order.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.userid
     *
     * @param userid the value for xt_order.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.amount
     *
     * @return the value of xt_order.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.amount
     *
     * @param amount the value for xt_order.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.amount_first
     *
     * @return the value of xt_order.amount_first
     *
     * @mbg.generated
     */
    public Double getAmountFirst() {
        return amountFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.amount_first
     *
     * @param amountFirst the value for xt_order.amount_first
     *
     * @mbg.generated
     */
    public void setAmountFirst(Double amountFirst) {
        this.amountFirst = amountFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.months
     *
     * @return the value of xt_order.months
     *
     * @mbg.generated
     */
    public Integer getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.months
     *
     * @param months the value for xt_order.months
     *
     * @mbg.generated
     */
    public void setMonths(Integer months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.amount_month
     *
     * @return the value of xt_order.amount_month
     *
     * @mbg.generated
     */
    public Double getAmountMonth() {
        return amountMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.amount_month
     *
     * @param amountMonth the value for xt_order.amount_month
     *
     * @mbg.generated
     */
    public void setAmountMonth(Double amountMonth) {
        this.amountMonth = amountMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.status
     *
     * @return the value of xt_order.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.status
     *
     * @param status the value for xt_order.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_order.createdate
     *
     * @return the value of xt_order.createdate
     *
     * @mbg.generated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_order.createdate
     *
     * @param createdate the value for xt_order.createdate
     *
     * @mbg.generated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }
}