package com.kx.exam.model;

public class Takeoff_order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_takeoff_order.takeoff_orderid
     *
     * @mbg.generated
     */
    private String takeoffOrderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_takeoff_order.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_takeoff_order.productid
     *
     * @mbg.generated
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_takeoff_order.amount_first
     *
     * @mbg.generated
     */
    private Double amountFirst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_takeoff_order.months
     *
     * @mbg.generated
     */
    private Integer months;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_takeoff_order.amount_month
     *
     * @mbg.generated
     */
    private Double amountMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_takeoff_order.bankno
     *
     * @mbg.generated
     */
    private String bankno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_takeoff_order.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_takeoff_order.takeoff_orderid
     *
     * @return the value of xt_takeoff_order.takeoff_orderid
     *
     * @mbg.generated
     */
    public String getTakeoffOrderid() {
        return takeoffOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_takeoff_order.takeoff_orderid
     *
     * @param takeoffOrderid the value for xt_takeoff_order.takeoff_orderid
     *
     * @mbg.generated
     */
    public void setTakeoffOrderid(String takeoffOrderid) {
        this.takeoffOrderid = takeoffOrderid == null ? null : takeoffOrderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_takeoff_order.userid
     *
     * @return the value of xt_takeoff_order.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_takeoff_order.userid
     *
     * @param userid the value for xt_takeoff_order.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_takeoff_order.productid
     *
     * @return the value of xt_takeoff_order.productid
     *
     * @mbg.generated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_takeoff_order.productid
     *
     * @param productid the value for xt_takeoff_order.productid
     *
     * @mbg.generated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_takeoff_order.amount_first
     *
     * @return the value of xt_takeoff_order.amount_first
     *
     * @mbg.generated
     */
    public Double getAmountFirst() {
        return amountFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_takeoff_order.amount_first
     *
     * @param amountFirst the value for xt_takeoff_order.amount_first
     *
     * @mbg.generated
     */
    public void setAmountFirst(Double amountFirst) {
        this.amountFirst = amountFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_takeoff_order.months
     *
     * @return the value of xt_takeoff_order.months
     *
     * @mbg.generated
     */
    public Integer getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_takeoff_order.months
     *
     * @param months the value for xt_takeoff_order.months
     *
     * @mbg.generated
     */
    public void setMonths(Integer months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_takeoff_order.amount_month
     *
     * @return the value of xt_takeoff_order.amount_month
     *
     * @mbg.generated
     */
    public Double getAmountMonth() {
        return amountMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_takeoff_order.amount_month
     *
     * @param amountMonth the value for xt_takeoff_order.amount_month
     *
     * @mbg.generated
     */
    public void setAmountMonth(Double amountMonth) {
        this.amountMonth = amountMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_takeoff_order.bankno
     *
     * @return the value of xt_takeoff_order.bankno
     *
     * @mbg.generated
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_takeoff_order.bankno
     *
     * @param bankno the value for xt_takeoff_order.bankno
     *
     * @mbg.generated
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_takeoff_order.order_status
     *
     * @return the value of xt_takeoff_order.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_takeoff_order.order_status
     *
     * @param orderStatus the value for xt_takeoff_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }
}